name: booking_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  characters: ^1.4.0
  google_fonts: ^6.3.2
  shimmer: ^3.0.0
  google_nav_bar: ^5.0.7
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  random_string: ^2.3.1
  google_sign_in: ^6.2.2
  flutter_riverpod: ^3.0.3
  cloud_firestore: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
